SELECT *
FROM CUSTOMER
LIMIT 20
    
--REVENUE GENERATED BY MALE N FEMALE CUSTOMERS
SELECT "Gender", SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY "Gender";

--CUSTOMERS SPENT MORE THAN AVG PURCHASE AMT DESPITE DISCOUNT
SELECT "Customer ID", "Purchase Amount (USD)"
FROM customer
WHERE "Discount Applied" = 'Yes'
AND "Purchase Amount (USD)" >= (
    SELECT AVG("Purchase Amount (USD)")
    FROM customer
);

--TOP 5 PRODUCTS WITH HIGHEST AVG REVIEW RATING
SELECT "Item Purchased",
       ROUND(AVG("Review Rating"::numeric), 2) AS "Average Product Rating"
FROM customer
GROUP BY "Item Purchased"
ORDER BY "Average Product Rating" DESC
LIMIT 5;

--Average Purchase Amounts between Standard and Express Shipping.
SELECT "Shipping Type",
       ROUND(AVG("Purchase Amount (USD)"::numeric), 2) AS avg_purchase
FROM customer
WHERE "Shipping Type" IN ('Standard','Express')
GROUP BY "Shipping Type";

--Compare average spend and total revenue between subscribers and non-subscribers.
SELECT "Subscription Status",
       COUNT("Customer ID") AS total_customers,
       ROUND(AVG("Purchase Amount (USD)"::numeric),2) AS avg_spend,
       ROUND(SUM("Purchase Amount (USD)"::numeric),2) AS total_revenue
FROM customer
GROUP BY "Subscription Status"
ORDER BY total_revenue DESC, avg_spend DESC;

--5 products having the highest percentage of purchases with discounts applied
SELECT "Item Purchased",
       ROUND(
           100.0 * SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
           2
       ) AS discount_rate
FROM customer
GROUP BY "Item Purchased"
ORDER BY discount_rate DESC
LIMIT 5;

--Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS (
    SELECT "Customer ID",
           "Previous Purchases",
           CASE
               WHEN "Previous Purchases" = 1 THEN 'New'
               WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)

SELECT customer_segment,
       COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

--revenue contribution of each age group
SELECT 
    CASE
        WHEN "Age" < 25 THEN 'Under 25'
        WHEN "Age" BETWEEN 25 AND 40 THEN '25-40'
        WHEN "Age" BETWEEN 41 AND 60 THEN '41-60'
        ELSE '60+'
    END AS age_group,
    
    SUM("Purchase Amount (USD)"::numeric) AS total_revenue

FROM customer

GROUP BY age_group
ORDER BY total_revenue DESC;

--Find the total revenue generated by each customer age group and show which age group contributes the most revenue.
WITH age_groups AS (
    SELECT 
        CASE 
            WHEN "Age" < 25 THEN 'Under 25'
            WHEN "Age" BETWEEN 25 AND 40 THEN '25-40'
            WHEN "Age" BETWEEN 41 AND 60 THEN '41-60'
            ELSE '60+'
        END AS age_group,
        "Purchase Amount (USD)"::numeric AS purchase_amount
    FROM customer
)
    
--Find highest revenue made by age groups
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM age_groups
GROUP BY age_group
ORDER BY total_revenue DESC;


